server: 
  port: 6001

spring:
  application:
    name: zull
eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:9003/eureka/,http://127.0.0.1:9002/eureka/,http://127.0.0.1:9001/eureka/
  instance: 
    instance-id: zull6001                        #自定义服务名称信息
    prefer-ip-address: true                                   #访问路径可以显示IP地址

zuul:
  prefix: /MyDemo
  ignored-services: provider
  routes:
    mydept.serviceId: provider
    mydept.path: /provider1/** 
       
info: 
  app.name: microservice-zull
  company.name: www.lzj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
